
pipeline {
   agent any
   stages {
      stage('Hello') {
         steps {
          sh label: '', 
           script: 
           '''
           cd spring-petclinic-config-server/
           sudo cp -r target /var/lib/jenkins/aditya
           '''
         } 
      }
   }
}
