//@Author - Aditya Malviya
//@Date   - 09-07-2020
//Purpose - Jenkins file for cMuse CI Pipeline.

pipeline {
   agent any
   stages {
      stage('Pull Repo1') {
         steps {
          sh label: '', 
           script: 
           '''
           cd spring-petclinic-config-server/
           mvn clean package
           sudo cp -r target /var/lib/jenkins/aditya
           cd ..
           sudo rm -rf *
           '''
         } 
      }
      stage('Pull Repo2') {
         steps {
          checkout changelog: false, poll: false, 
          scm: [$class: 'GitSCM', branches: [[name: '*/master']], 
          doGenerateSubmoduleConfigurations: false, 
          extensions: [], 
          submoduleCfg: [], 
          userRemoteConfigs: [[url: 'https://github.com/aditya-malviya/JavaHelloWorld.git']]]
         } 
      }

      stage('Copy files') {
         steps {
          sh label: '', 
           script: 
           '''
           cd /var/lib/jenkins/aditya
           cp -r target/ /var/lib/jenkins/workspace/pet-clinic-config-service/src
           cd /var/lib/jenkins/workspace/pet-clinic-config-service
           git add .
           git commit -m "added"
           git push origin
           '''
         } 
      }
   }
}
