pipeline {
   agent any
   stages {
      stage('Hello') {
         steps {
          sh label: '', 
           script: 
           '''
           echo "hello"
           cd spring-petclinic-config-server
           mvn clean package
           '''
         } 
      }
   }
}
